apiVersion: v1
kind: Service
metadata:
  name: wisecow-service
spec:
  type: NodePort
  selector:
    app: wisecow
  ports:
    - protocol: TCP
      port: 80          # Service port
      targetPort: 4499  # Pod container port
      nodePort: 30080   # Optional NodePort

