apiVersion: v1
kind: Service
metadata:
  name: wisecow-service
spec:
  type: ClusterIP
  selector:
    app: wisecow
  ports:
    - protocol: TCP
      port: 80        # service port (what Ingress uses)
      targetPort: 4499  # FIXED: match container port

