name: CI/CD Pipeline

on:
  push:
    branches:
      - main

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3

      - name: Log in to Docker Hub
        uses: docker/login-action@v3
        with:
          username: ${{ secrets.MUBEEN07 }}       # Your Docker Hub username secret
          password: ${{ secrets.DOCKER_PASSWORD }} # Your Docker Hub PAT secret

      - name: Build Docker image
        run: |
          docker build -t ${{ secrets.MUBEEN07 }}/wisecow-app:latest .

      - name: Push Docker image
        run: |
          docker push ${{ secrets.MUBEEN07 }}/wisecow-app:latest

      - name: Set up kubectl
        uses: azure/setup-kubectl@v3
        with:
          version: '1.34.0'

      - name: Apply Kubernetes manifests
        run: |
          kubectl apply -f wisecow-deployment.yaml
          kubectl apply -f wisecow-service.yaml
          kubectl apply -f wisecow-ingress.yaml

